package.json
src/components/NetworkBar/NetworkBar.tsx

This PR fixes issue where css is not read in component.

fix: accept css side effect

---

package-lock.json
package.json
src/components/AddressBook/AddressBook.tsx
src/components/AddressBook/AddressBookLocal/AddressBookLocal.tsx
src/components/AddressBook/AddressBookTableRow.tsx
src/components/AddressBook/AddressBookThirdParty/AddressBookThirdParty.test.tsx
src/components/AddressBook/AddressBookThirdParty/AddressBookThirdParty.tsx

This PR is parallel to https://github.com/TradeTrust/tradetrust-website/pull/260, adding a source to resolved identity.

feat: added identity source field

---

src/index.tsx

- exposing the overlay content component

fix: exposing overlay content

---

package.json
src/common/context/OverlayContext.tsx
src/components/AddressBook/AddressBook.stories.tsx
src/components/AddressBook/AddressBook.tsx
src/components/AddressBook/AddressBookLocal/AddressBookLocal.test.tsx
src/components/AddressBook/AddressBookLocal/AddressBookLocal.tsx
src/components/UI/Dropdown/Dropdown.tsx

- updated the dropdown text to be truncated
- updated the addressbook to update with the latest addressbook

fix: addressbook

---

src/components/AddressBook/AddressBook.stories.tsx
src/components/AddressBook/AddressBook.tsx
src/components/AddressBook/AddressBookTableRow.tsx
src/components/UI/Pagination/Pagination.tsx

- disabled left and right pagination if reached end
- pass limit and offset as options
- show up variations in storybook to see easier
- fix key warning in button loop

fix: pagination 1

---

src/components/AddressBook/AddressBook.tsx
src/components/UI/Dropdown/Dropdown.stories.tsx
src/components/UI/Dropdown/Dropdown.tsx
src/tailwind.js

- updated the dropdown component to be more flexible

feat: update dropdown

---

src/index.tsx

fix: dropdown export

---

src/components/UI/Dropdown/Dropdown.stories.tsx
src/components/UI/Dropdown/Dropdown.tsx

- updated the z-index of the dropdown box.

fix: dropdown z index

---

README.md
package.json
src/components/AddressBook/AddressBook.tsx
src/components/AddressBook/AddressBookTableRow.tsx
src/components/AddressResolver/AddressesTable.tsx
src/components/NetworkBar/NetworkBar.tsx
src/components/UI/Button/Button.tsx
src/components/UI/Dropdown/Dropdown.stories.tsx
src/components/UI/Dropdown/Dropdown.tsx
src/components/UI/Loader/Loader.stories.tsx
src/components/UI/Overlay/Overlay.tsx
src/components/UI/Overlay/OverlayContent/DocumentTransferMessage.tsx
src/components/UI/Overlay/OverlayContent/OverlayContent.tsx
src/styles/abstracts/mixin.tsx
src/styles/abstracts/variables.tsx
src/tailwind.js

- consolidate and remove stray styles
- standardised to tailwind colors naming convention

fix: cleanup twconfig

---

src/components/AddressBook/AddressBook.tsx
src/components/AddressResolver/AddressesTable.tsx
src/components/AddressResolver/EndpointEntry/EndpointEntry.tsx
src/components/NetworkBar/NetworkBar.tsx
src/components/UI/Input/Input.stories.tsx
src/components/UI/Input/Input.tsx
src/components/UI/Overlay/Overlay.tsx
src/components/UI/Overlay/OverlayContent/DocumentTransferMessage.tsx
src/components/UI/Overlay/OverlayContent/OverlayContent.tsx
src/styles/abstracts/mixin.tsx
src/tailwind.js

- updated components that were using vars to use tailwind config constants.

chore: remove vars from components

---

package.json
src/tailwind.js
tailwind.config.js

- only purge for this repo
- share the unpurged config to tt and creator

fix: shift purge option

---

package-lock.json
package.json
src/components/AddressBook/AddressBook.stories.tsx
src/components/AddressBook/AddressBook.tsx
src/components/AddressBook/AddressBookLocal/AddressBookLocal.test.tsx
src/components/AddressBook/AddressBookLocal/AddressBookLocal.tsx
src/components/AddressBook/AddressBookTableRow.tsx
src/components/AddressBook/AddressBookThirdParty/AddressBookThirdParty.test.tsx
src/components/AddressBook/AddressBookThirdParty/AddressBookThirdParty.tsx
src/components/UI/Pagination/Pagination.stories.tsx
src/components/UI/Pagination/Pagination.tsx
src/components/UI/Pagination/PaginationNumber.tsx
src/components/UI/Pagination/index.tsx

- Added the pagination for address book
- for both local address book and third party address book

feat: added pagination for address book

---

package-lock.json
package.json
tailwind.config.js

- include src folder so application side can include to purge

fix: src folder

---

package-lock.json
package.json
src/components/AddressBook/AddressBook.stories.tsx
src/components/AddressBook/AddressBook.tsx
src/components/AddressBook/AddressBookLocal/AddressBookLocal.test.tsx
src/components/AddressBook/AddressBookLocal/AddressBookLocal.tsx
src/components/AddressBook/AddressBookTableRow.tsx
src/components/AddressBook/AddressBookThirdParty/AddressBookThirdParty.test.tsx
src/components/AddressBook/AddressBookThirdParty/AddressBookThirdParty.tsx
src/components/AddressResolver/AddressesTable.tsx
src/components/UI/Overlay/Overlay.tsx
src/tailwind.css

- show error if entityLookup feature does not exist
- includes fix for endpoint trailing slash -> `"@govtechsg/address-identity-resolver": "^1.4.1"`
- story: https://www.pivotaltracker.com/story/show/175433574

feat: entityLookup error

---

.storybook/preview-head.html
package.json
src/components/UI/Button/Button.stories.tsx
src/components/UI/Dropdown/Dropdown.stories.tsx
src/components/UI/Dropdown/Dropdown.tsx
src/components/UI/Overlay/Overlay.tsx
src/components/UI/Overlay/OverlayContent/DeleteResolverConfirmation.tsx
src/components/UI/Overlay/OverlayContent/DocumentTransferMessage.tsx
src/styles/abstracts/mixin.tsx
src/tailwind.js
tailwind.config.js

- remove font in exported tw config
- drop source sans, montserrat

fix: roboto font

---

package.json
src/components/NetworkBar/Network.test.tsx
src/components/NetworkBar/NetworkBar.stories.tsx
src/components/NetworkBar/NetworkBar.tsx
src/tailwind.js

- refactor the network bar to support children so both TT and Creator can use it.

chore: refactor network bar to support children.

---

src/components/AddressBook/AddressBook.tsx
src/components/AddressBook/AddressBookLocal/AddressBookLocal.tsx
src/components/AddressBook/AddressBookTableRow.tsx
src/components/AddressBook/AddressBookThirdParty/AddressBookThirdParty.tsx
src/components/UI/Dropdown/Dropdown.tsx

- make network optional, creator has a case where config is "logged out"

fix: addressbook network

---

src/components/AddressBook/AddressBook.tsx
src/components/UI/Dropdown/Dropdown.tsx

- bg-color should be determined from dropdown, rather than be fixed in it

fix: dropdown color

---

src/components/UI/Dropdown/Dropdown.tsx

readjust the z-index for better close of dropdown

fix: readjust the z-index for the dropdown

---

src/components/UI/Pagination/Pagination.test.tsx
src/components/UI/Pagination/Pagination.tsx

- the idea is we have a range to determine when to show truncation

refactor: pagination logic

---

src/components/UI/Pagination/Pagination.test.tsx
src/components/UI/Pagination/Pagination.tsx
src/components/UI/Pagination/PaginationBox.tsx

- remove the functionality of the truncation., as requested from the POs.

fix: update pagination based on feedback from PO to remove the expansion of the truncated boxes.

---

src/components/UI/Loader/LoaderSpinner.tsx
src/tailwind.css

- Updated the spinner class to use the one provided in tailwind

fix: fix the loader spinner to use tailwind spinner class

---

src/components/AddressBook/AddressBook.tsx
src/components/UI/Overlay/Overlay.stories.tsx
src/components/UI/Overlay/Overlay.tsx
src/components/UI/Overlay/OverlayContent/DeleteResolverConfirmation.tsx
src/components/UI/Overlay/OverlayContent/DocumentTransferMessage.tsx
src/components/UI/Overlay/OverlayContent/OverlayContent.tsx
src/components/UI/Overlay/OverlayContent/Textual.tsx
src/components/UI/Overlay/OverlayContent/Youtube.tsx

- scoped styles making life hard to customize by tw classes

fix: remove overlay scoped styles

---

src/components/NavigationBar/MockNavigationBar.tsx
src/components/NavigationBar/NavigationBar.stories.tsx
src/components/NavigationBar/NavigationBar.test.tsx
src/components/NavigationBar/NavigationBar.tsx
src/components/NavigationBar/NavigationBarItem.tsx
src/tailwind.css
src/tailwind.js

- can be clean up further
- remove repeated classes
- avoid scoped styles as much as possible
- passed in menu children markup be as simple as possible

fix: navbar redesign

---

README.md
package-lock.json
package.json
src/common/styles/Table.tsx
src/components/AddressBook/AddressBook.tsx
src/components/AddressBook/AddressBookTableRow.tsx
src/components/AddressBook/AddressBookThirdParty/AddressBookThirdParty.tsx
src/components/AddressBook/CsvUploadButton.tsx
src/components/AddressResolver/AddressResolver.tsx
src/components/AddressResolver/AddressesTable.tsx
src/components/ErrorPage/ErrorPage.stories.tsx
src/components/ErrorPage/ErrorPage.tsx
src/components/NavigationBar/MockNavigationBar.tsx
src/components/NavigationBar/NavigationBar.tsx
src/components/NavigationBar/NavigationBarItem.tsx
src/components/NetworkBar/NetworkBar.stories.tsx
src/components/NetworkBar/NetworkBar.tsx
src/components/UI/Button/Button.stories.tsx
src/components/UI/Button/Button.tsx
src/components/UI/Dropdown/Dropdown.stories.tsx
src/components/UI/Dropdown/Dropdown.tsx
src/components/UI/Input/Input.tsx
src/components/UI/Nav/Nav.tsx
src/components/UI/Overlay/OverlayContent/DeleteResolverConfirmation.tsx
src/components/UI/Overlay/OverlayContent/DocumentTransferMessage.tsx
src/components/UI/Overlay/OverlayContent/OverlayContent.tsx
src/components/UI/Pagination/Pagination.tsx
src/components/UI/Pagination/PaginationBox.tsx
src/tailwind.js

BREAKING CHANGE: update tailwind to v2

---

src/components/UI/Overlay/OverlayContent/OverlayContent.tsx
src/tailwind.css

fix: text size

---

src/components/UI/Pagination/Pagination.tsx
src/components/UI/Pagination/PaginationBox.tsx
src/tailwind.js

https://www.pivotaltracker.com/story/show/178211157

fix: redesign of pagination component

---

src/components/UI/Overlay/Overlay.mock.tsx
src/components/UI/Overlay/Overlay.stories.tsx
src/components/UI/Overlay/Overlay.test.tsx
src/components/UI/Overlay/OverlayContent/OverlayContent.tsx
src/components/UI/Pagination/Pagination.tsx
src/components/UI/Pagination/PaginationBox.tsx

- add testid
- fix pagination style

fix: add testid

---

src/components/UI/Footer/Footer.tsx

- missed out certain styles for the footer.

fix: footer css

---

src/components/AddressBook/AddressBook.tsx
src/components/UI/Dropdown/Dropdown.stories.tsx
src/components/UI/Dropdown/Dropdown.tsx
src/components/UI/Input/Input.tsx

- refactor passing in of css classes

fix: input dropdown styles

---

src/components/UI/Pagination/Pagination.stories.tsx
src/components/UI/Pagination/Pagination.test.tsx
src/components/UI/Pagination/Pagination.tsx

- abstracted logic to here
- added simple example on how to use in storybook

fix: pagination numbering

---

src/components/NavigationBar/NavigationBarItem/NavigationBarItem.tsx

- Changing dropdown list rotation
- Shifting dropdown list arrow nearer to the label
- Fix label button rounded layering and double shadowing

fix: update-navbar-design

---

.storybook/main.js
package-lock.json
package.json
webpack.config.js

- webpack v5 + sb v6.3 upwards

fix: webpack 5

---

src/components/NavigationBar/NavigationBar.mock.tsx
src/components/NavigationBar/NavigationBar.stories.tsx
src/components/NavigationBar/NavigationBar.test.tsx
src/components/NavigationBar/NavigationBar.tsx
src/components/NavigationBar/NavigationBarItem/NavigationBarItem.tsx
src/components/UI/Button/Button.tsx
src/tailwind.js

- dropdown should collapse when click on other links
- refactor + clean up

fix: navbar dropdown

---

src/components/AddressResolver/EndpointEntry/EndpointEntry.tsx
src/components/UI/Icon/Icon.stories.tsx
src/components/UI/Icon/Icon.tsx
src/components/UI/Overlay/OverlayContent/AddResolverConfirmation.tsx
src/components/UI/Overlay/OverlayContent/DocumentTransferMessage.tsx
src/components/UI/Overlay/OverlayContent/OverlayContent.tsx
src/utils/index.ts

redesign of viewer page components which would be used in tt-web upon viewing verified documents

feat: redesign viewer page components

---

package.json
src/components/AddressResolver/AddressesTable.tsx
src/components/AddressResolver/EndpointEntry/EndpointEntry.tsx
src/components/NavigationBar/NavigationBarItem/NavigationBarItem.tsx
src/components/UI/Input/Input.tsx

fix: address resolver styles

---

src/components/NavigationBar/NavigationBar.mock.tsx
src/components/NavigationBar/NavigationBar.tsx
src/components/NavigationBar/NavigationBarItem/NavigationBarItem.tsx
src/components/UI/Button/Button.tsx
src/components/UI/Input/Input.tsx
src/tailwind.css

- buttons variations, inputs, navbar fixes

fix: redesign loose ends

---

src/components/AddressResolver/AddressResolver.tsx
src/components/NavigationBar/NavigationBar.mock.tsx
src/components/NavigationBar/NavigationBarItem/NavigationBarItem.tsx
src/components/UI/Button/Button.stories.tsx
src/components/UI/Button/Button.tsx
src/tailwind.js

fix: button styles

---

src/components/UI/Footer/Footer.tsx
src/components/UI/Footer/helpers.tsx

- to cater to additional new column now that there are more pages

fix: footer columns

---

package-lock.json
package.json
src/components/UI/Input/Input.tsx

feat: remove twin macro

---

src/tailwind.js

fix: add colors

---

src/components/UI/Dropdown/Dropdown.tsx

- wanna reuse this in react json form schema custom widget

fix: dropdown prevent default

---

src/components/UI/Dropdown/Dropdown.tsx

- allow to edit root div classes

fix: dropdown root class

---

src/components/AddressBook/AddressBook.tsx
src/components/AddressBook/AddressBookTableRow.tsx
src/components/UI/Dropdown/Dropdown.stories.tsx
src/components/UI/Dropdown/Dropdown.tsx
src/components/UI/Nav/Nav.tsx
src/components/UI/Overlay/OverlayContent/OverlayContent.tsx

- remove fixed w and h
- break words

fix: responsive fixes

---

.storybook/main.js
babel.config.json
package-lock.json
package.json
src/components/NavigationBar/NavigationBar.tsx
src/components/UI/Button/Button.tsx
src/components/UI/Loader/LoaderSpinner.tsx
src/tailwind.css
tailwind.config.js

Removed emotion to allow for server-side rendering of components

feat: remove emotion

---

src/index.tsx

forgot to export toggle component

fix: forgot about export

---

package-lock.json
src/components/UI/Dropdown/Dropdown.stories.tsx
src/components/UI/Dropdown/Dropdown.tsx

https://www.pivotaltracker.com/story/show/180896522

feat: custom dropdown button

---

src/components/UI/Dropdown/Dropdown.stories.tsx
src/components/UI/Dropdown/Dropdown.tsx

changed dropdown button text to be customisable

feat: updated custom dropdown

---

integration/tests/overlay.spec.ts
src/common/context/OverlayContext.tsx
src/components/UI/Overlay/Overlay.tsx
src/components/UI/Overlay/OverlayContent/AddResolverConfirmation.tsx
src/components/UI/Overlay/OverlayContent/DeleteResolverConfirmation.tsx
src/components/UI/Overlay/OverlayContent/DocumentTransferMessage.tsx
src/components/UI/Overlay/OverlayContent/OverlayContent.tsx

Added closeOverlay function to context
Moved closeOverlay from Overlay's context to OverlayContext
NIL

feat/ added closeOverlay

---

src/components/AddressBook/AddressBookTableRow.tsx
src/components/AddressResolver/EndpointEntry/EndpointEntry.tsx
src/components/ErrorPage/ErrorPage.stories.tsx
src/components/UI/Nav/Nav.tsx
src/components/UI/Overlay/OverlayContent/AddResolverConfirmation.tsx
src/components/UI/Overlay/OverlayContent/DeleteResolverConfirmation.tsx
src/components/UI/Overlay/OverlayContent/DocumentTransferMessage.tsx
src/components/UI/Pagination/PaginationBox.tsx
src/components/UI/ProgressBar/ProgressBar.tsx

fix colors for components, to use new blue color

fix: update color to new blue

---

src/components/UI/Input/Input.tsx

fix: input border color

---

src/components/ErrorPage/ErrorPage.tsx

- https://www.pivotaltracker.com/story/show/182283772
- current error page styles broken -> https://ui.tradetrust.io/?path=/story/error-errorpage--default
- current pr fix -> https://deploy-preview-133--tradetrust-ui-components-storybook.netlify.app/?path=/story/error-errorpage--default

fix: error page

---

src/components/NavigationBar/NavigationBar.stories.tsx
src/components/NavigationBar/NavigationBar.tsx

fix: nav bar bg-color

---

src/components/AddressBook/AddressBookLocal/AddressBookLocal.tsx
src/components/AddressBook/AddressBookThirdParty/AddressBookThirdParty.tsx
src/components/AddressResolver/AddressesTable.tsx
src/components/AddressResolver/EndpointEntry/EndpointEntry.tsx
src/components/NavigationBar/NavigationBarItem/NavigationBarItem.tsx
src/components/UI/Button/Button.tsx
src/components/UI/Dropdown/Dropdown.stories.tsx
src/components/UI/Footer/Footer.tsx
src/components/UI/Footer/helpers.tsx
src/components/UI/Nav/Nav.tsx
src/tailwind.css

- Updated some font size and weight for the components to align with TT web and creator

fix: font size and weight

---

src/components/NavigationBar/NavigationBar.tsx

- Align navigation bar items and logo

fix: align navigation bar

---

src/components/UI/Overlay/OverlayContent/OverlayContent.tsx

- Update overlay content component's 'X' button to handle custom styles.

fix: update overlay content cross button to have custom styles

---

src/components/UI/Footer/Footer.stories.tsx
src/components/UI/Footer/Footer.test.tsx
src/components/UI/Footer/Footer.tsx
src/components/UI/Footer/helpers.tsx
src/components/UI/Footer/types.ts

update footer for policy and terms button
- update footer bottom section to cater for dynamic buttons

fix: update footer for policy and terms

---

src/components/UI/Footer/Footer.tsx
src/components/UI/Pagination/Pagination.tsx

Fix accessibility for TT-web components.
- Update missing alt and aria-label
https://www.pivotaltracker.com/n/projects/2424361/stories/183461727

fix: update with alt and aria-label

---

.github/workflows/release.yml
integration/tests/address-resolver-entry-error.spec.ts
package.json

- probably [not recommend](https://github.com/actions/cache/blob/main/examples.md#node---npm) to cache node modules
- network error covered by [unit](https://github.com/TradeTrust/tradetrust-ui-components/blob/a4f5de3a74facb3036a0c4a5ae90477e0ab799b8/src/components/AddressResolver/EndpointEntry/EndpointEntry.test.tsx#L66-L77)

chore: ci update

---

.github/workflows/release.yml
package-lock.json
package.json

chore: pin semantic release

---

.storybook/main.js
package-lock.json
package.json
postcss.config.js

- remove postcss
- use tailwind cli directly, let them handle any css post processing if any

feat: update tailwind

---

src/components/UI/Overlay/OverlayContent/Youtube.tsx
src/tailwind.css

- [supported](https://tailwindcss.com/docs/aspect-ratio) out of box nowadays.

fix: aspect ratio

---

.github/workflows/release.yml
package.json
src/components/UI/Overlay/OverlayContent/DocumentTransferMessage.tsx

- Update surrender wording for Token Registry v5 changes
- What are the changes made in this pull request?
- Replaced all surrender to return to issuer or equivalent
BREAKING CHANGE: alpha release for v3

feat: rename surrender

---

.github/workflows/release.yml
package.json
src/components/UI/Overlay/OverlayContent/DocumentTransferMessage.tsx

- Release new version for updated copywriting for token-registry v5
BREAKING CHANGE: new release for token-registry v5

feat: BREAKING CHANGE: updated components for token registry v5

---

src/components/UI/Overlay/OverlayContent/DocumentTransferMessage.tsx
src/components/UI/Overlay/OverlayContent/ProviderTimeoutMessage.tsx

updated target="_blank" with rel="noreferrer noopener"

feat: update rel

---

package-lock.json
package.json
src/components/AddressBook/AddressBook.tsx
src/components/AddressBook/AddressBookLocal/AddressBookLocal.test.tsx
src/components/AddressBook/AddressBookLocal/AddressBookLocal.tsx
src/components/AddressBook/AddressBookThirdParty/AddressBookThirdParty.tsx
src/components/AddressResolver/AddressesTable.tsx
src/components/AddressResolver/EndpointEntry/EndpointEntry.test.tsx
src/components/AddressResolver/EndpointEntry/EndpointEntry.tsx
src/components/UI/Overlay/OverlayContent/MessageAddressResolver.tsx

- repalce @govtechsg/address-identity-resolver package

fix: address-identity-resolver package

---

.github/workflows/release.yml
src/components/UI/Dropdown/Dropdown.tsx

- Update dropdown text, centralise text

fix: dropdown text

---

package-lock.json
package.json
src/components/NavigationBar/NavigationBar.tsx
src/components/UI/Dropdown/Dropdown.tsx
src/components/UI/Footer/helpers.tsx
src/components/UI/Footer/types.ts
webpack.config.ts

- **fix: update css for dropdown and navigationbar**
- **fix: footer**

fix: update component for footer and navigation bar

---

src/components/UI/Overlay/Overlay.tsx

- update overlay effect, prevent scroll

fix: overlay

---

src/components/UI/Dropdown/Dropdown.stories.tsx
src/components/UI/Footer/Footer.tsx

fix: footer gap

---

src/components/UI/Overlay/OverlayContent/DocumentTransferMessage.tsx

- Allow custom footer for overlay

fix: allow custom footer for overlay

---

src/components/UI/Footer/Footer.tsx
src/components/UI/Footer/helpers.tsx

Updated footer design for mobile view
[Jira Ticket](https://afa-cdi.atlassian.net/browse/TT-603?atlOrigin=eyJpIjoiYmU0YjhmOWIwYzYxNDBkMTg3NTYyYmRhNjIwNjBiMDIiLCJwIjoiaiJ9)

feat: mobile view design update

---

src/components/UI/Dropdown/Dropdown.tsx

fix: dropdown popup with portal
